### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by skybarberom** [oliverjrose99/Recordurbate#79]
As an improvement, it could be nice to have a docker version of the project with its docker file. It would be easier to deploy/maintain

**Comment by 81hvac1k** [comment]
I agree this would be nice, in the meantime i created my own Dockerfile & docker-compose. 
It's far from perfect, but it works. 
Here are the steps i took: 


first clone the repo, and make any special changes to the config files. For example i  changed `youtube-dl` to `yt-dlp` and the output to be to `/videos` 
Create script file named `entrypoint.sh` containing 
```
#!/bin/sh
python3 Recordurbate.py import list.txt
python3 Recordurbate.py start
sleep infinite
```
(the sleep here is far from ideal and goes against how containers should work. But i couldn't figure out how to make docker register the correct process and keep the container running.)

Make a reqirements file containing: 
```
requests
yt-dlp
```
Create your list of streamers in a file named `list.txt`

Then create Dockerfile 

``` 
FROM python:alpine

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN apk add ffmpeg
COPY ./recordurbate ./
RUN mkdir /videos
COPY entrypoint.sh ./
ENTRYPOINT ./entrypoint.sh
 ```


Then docker-compose: 
```
version: '3.9'

services:

  python:
    build:
      context: .
    container_name: recordurbate
    volumes:
      - /storage/media:/videos # change this mountpoint to suit your setup
      - ./list.txt:/usr/src/app/list.txt:ro 
``` 

Make sure `Dockerfile`, `docker-compose.yml`, `entrypoint.sh`, `requirements.txt` & `list.txt` are placed in the folder Recordurbate (in the same folder as the README.md file) and then run the command: 

``` docker compose up -d ```
